"""Initial schema setup

Revision ID: 992b9ace03da
Revises: 
Create Date: 2025-10-27 19:53:49.908354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992b9ace03da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipient_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signup_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signup_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_is_archived'), ['is_archived'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_is_archived'))

    with op.batch_alter_table('signup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signup_user_id'))
        batch_op.drop_index(batch_op.f('ix_signup_trip_id'))

    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipient_user_id'))

    # ### end Alembic commands ###
